[package]
name = "envelope_contract"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
sak_contract_std = { path = "../../source/sak_contract_std" }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.59"
type_extension = { path = "../../source/type_extension" }
sak_crypto = { path = "../../source/sak_crypto" }

[dev-dependencies]
sak_test_utils = { path = "../../source/sak_test_utils" }
sak_vm = { path = "../../source/sak_vm" }
tokio = { version = "1.12.0", features = ["full"] }
