[package]
name = "wasm_postprocess"
version = "0.1.0"
edition = "2018"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sak_logger = { path = "../../source/sak_logger" }
sak_dir = { path = "../../source/sak_dir" }
sak_contract_std = { path = "../../source/sak_contract_std" }
chrono = "0.4"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.59"
serde_bytes = "0.11.6"
walrus = "0.18.0"
wasm-bindgen-multi-value-xform = "=0.2.69"
wasm-bindgen-wasm-conventions = "=0.2.69"
wit-text = "0.8.0"
wit-validator = "0.2.1"
wit-walrus = "0.5.0"
clap = { version = "3.1.6", features = ["cargo"] }
colored = "2"
wabt = "0.9.0"

[dev-dependencies]
sak_test_utils = { path = "../../source/sak_test_utils" }

[lib]
doctest = false # until stable beta is released

[[bin]]
name = "cli"
path = "src/bin/main.rs"
