[package]
name = "saksaha"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_bytes = "0.11.6"
sak_dir = { path = "../sak_dir" }
sak_logger = { path = "../sak_logger" }
sak_rpc_interface = { path = "../sak_rpc_interface" }
sak_dist_ledger_config = { path = "../sak_dist_ledger_config" }
type_extension = { path = "../type_extension" }
sak_crypto = { path = "../sak_crypto" }
sak_contract_std = { path = "../sak_contract_std" }
sak_types = { path = "../sak_types" }
sak_proof = { path = "../sak_proof" }
tui = "0.18.0"
tui-logger = "0.8"
crossterm = "0.23"
tokio = { version = "1.20.0", features = ["full"] }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.59"
clap = { version = "3.2.14", features = ["cargo"] }
serde_yaml = "0.8"
hyper = { version = "0.14", features = ["full"] }

[dev-dependencies]
sak_test_utils = { path = "../sak_test_utils" }
