[package]
name = "sak_vm"
version = "0.1.0"
edition = "2018"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sak_kv_db = { path = "../sak_kv_db" }
sak_vm_interface = { path = "../sak_vm_interface" }
sak_contract_std = { path = "../sak_contract_std" }
sak_logger = { path = "../sak_logger" }
sak_mrs = { path = "../sak_mrs" }
sak_dir = { path = "../sak_dir" }
sak_crypto = { path = "../sak_crypto" }
sak_store_accessor = { path = "../sak_store_accessor" }
chrono = "0.4"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.59"
serde_bytes = "0.11.6"
tokio = { version = "1.21.2", features = ["full"] }
wasmtime = "1.0.1"

[dev-dependencies]
sak_test_utils = { path = "../sak_test_utils" }

[lib]
doctest = false # until stable beta is released
