[package]
name = "saksaha_wallet"
version = "0.1.0"
edition = "2021"
default-run = "wallet"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.12.0", features = ["full"] }
colored = "2"
log = "0.4.0"
clap = { version = "3.2.14", features = ["cargo"] }
futures = "0.3.21"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.59"
serde_bytes = "0.11.6"
hyper = { version = "0.14", features = ["full"] }
type_extension = { path = "../type_extension" }
sak_dist_ledger_meta = { path = "../sak_dist_ledger_meta" }
hyper_server = { path = "../hyper_server" }
hyper_rpc_router = { path = "../hyper_rpc_router" }
saksaha = { path = "../saksaha_rs" }
saksaha_network = { path = "../saksaha_network" }
sak_crypto = { path = "../sak_crypto" }
sak_types = { path = "../sak_types" }
sak_fs = { path = "../sak_fs" }
sak_logger = { path = "../sak_logger" }
sak_p2p_id = { path = "../sak_p2p_id" }
sak_contract_std = { path = "../sak_contract_std" }
sak_rpc_interface = { path = "../sak_rpc_interface" }
sak_kv_db = { path = "../sak_kv_db" }
sak_proofs = { path = "../sak_proofs" }
sak_utils_net = { path = "../sak_utils_net" }

[dev-dependencies]
sak_test_utils = { path = "../sak_test_utils" }
envelope_term = { path = "../../externals/envelope_term" }
envelope_contract = { path = "../../externals/envelope_contract" }

[[bin]]
name = "wallet"
path = "src/bin/wallet/main.rs"
