[workspace]

members = [
  "source/sak_logger",
  "source/saksaha",
  "source/sak_crypto",
  "source/sak_proofs",
  "source/sak_fs",
  "source/sak_kv_db",
  "source/sak_p2p_addr",
  "source/sak_p2p_ptable",
  "source/sak_p2p_frame",
  "source/sak_p2p_disc",
  "source/sak_p2p_id",
  "source/sak_p2p_trpt",
  "source/sak_task_queue",
  "source/sak_utils_time",
  "source/sak_utils_net",
  "source/sak_contract",
  "source/sak_blockchain",
  "source/sak_vm",

  # system contracts (each)
  "source/sak_ctrt_validator",

  # internals
  "internals/ci",

  # example
  "example/chat",
  "example/chat2",
]
