[workspace]

members = [
  "source/logger",
  "source/saksaha",
  "source/crypto",
  "source/file_system",
  "source/database",
  "source/proofs",
  "source/p2p_addr",
  "source/p2p_peer_table",
  "source/p2p_frame",
  "source/p2p_discovery",
  "source/p2p_identity",
  "source/p2p_transport",
  "source/p2p_transport_ops",
  "source/task_queue",
  "source/utils_time",
  "source/utils_net",
  "source/contract",

  # contracts
  "source/saksaha/src/contracts/validator",

  # internals
  "internals/ci",

  # example
  "example/chat",
  "example/chat2",
]
