#!/bin/bash
set -e

rm -rf ./target/wasm32-unknown-unknown/release/sak_ctr_messenger.wasm
rm -rf ./target/wasm32-unknown-unknown/release/sak_ctr_messenger.d
cd ./source/sak_ctr_messenger
cargo wasm
echo $PWD
cd ../../
cp ./target/wasm32-unknown-unknown/release/sak_ctr_messenger.wasm ~/work/saksaha/saksaha/source/sak_vm/src/v0/sak_ctr_messenger.wasm

cd ~/work/saksaha/
mkdir multivalue-util
cd multivalue-util
git clone git@github.com:vmx/wasm-multi-value-reverse-polyfill.git

cd wasm-multi-value-reverse-polyfill
cp ~/work/saksaha/saksaha/source/sak_vm/src/v0/sak_ctr_messenger.wasm .
cargo run sak_ctr_messenger.wasm 'init i32 i32' 'query i32 i32' 'execute i32 i32'

cp ./sak_ctr_messenger.wasm.multivalue.wasm ~/work/saksaha/saksaha/source/sak_vm/src/v0/sak_ctr_messenger.wasm

cd ~/work/saksaha/saksaha
rm -rf ../multivalue-util/
