#!/bin/bash

set -e


rm -rf ./source/sak_ctrt_validator/target
cd ./source/sak_ctrt_validator
cargo wasm
echo $PWD
cd ../../
cp ./target/wasm32-unknown-unknown/release/sak_ctrt_validator.wasm ~/work/saksaha/saksaha/source/sak_vm/src/v0/sak_ctrt_validator.wasm
# wasm2wat ~/work/saksaha/saksaha/source/sak_vm/src/v0/sak_ctrt_validator.wasm &> ./sak_ctrt_validator_before.wat

# util
cd ~/work/saksaha/saksaha
cd ..
mkdir multivalue-util
cd multivalue-util
git clone git@github.com:vmx/wasm-multi-value-reverse-polyfill.git

cd wasm-multi-value-reverse-polyfill
cp ~/work/saksaha/saksaha/source/sak_vm/src/v0/sak_ctrt_validator.wasm .
cargo run sak_ctrt_validator.wasm 'init i32 i32' 'query i32 i32' 'execute i32 i32'

cp ./sak_ctrt_validator.wasm.multivalue.wasm ~/work/saksaha/saksaha/source/sak_vm/src/v0/sak_ctrt_validator.wasm
cp ./sak_ctrt_validator.wasm.multivalue.wasm ~/work/saksaha/saksaha/check_result.wasm

cd ~/work/saksaha/saksaha
rm -rf ../multivalue-util/

wasm2wat ~/work/saksaha/saksaha/source/sak_vm/src/v0/sak_ctrt_validator.wasm &> ./sak_ctrt_validator.wat
# wasm-decompile  ~/work/saksaha/saksaha/source/sak_vm/src/v0/sak_ctrt_validator.wasm -o wasm.c
# ./ci dev
