[package]
name = "envelope_term"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
directories = "3.0"
sak_fs = { path = "../../source/sak_fs" }
sak_logger = { path = "../../source/sak_logger" }
sak_crypto = { path = "../../source/sak_crypto" }
sak_types = { path = "../../source/sak_types" }
saksaha = { path = "../saksaha_rs" }
log = "0.4"
tui = "0.18.0"
tui-logger = "0.8"
crossterm = "0.23"
tokio = { version = "1.20.0", features = ["full"] }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.59"
clap = { version = "3.2.14", features = ["cargo"] }
serde_yaml = "0.8"
unicode-width = "0.1.5"
chrono = "0.4"

[dev-dependencies]
sak_test_utils = { path = "../../source/sak_test_utils" }

[[bin]]
name = "envelope_term"
path = "src/bin/main.rs"
