[package]
name = "sak_store_interface"
version = "0.1.0"
edition = "2018"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# sak_logger = { path = "../sak_logger" }
sak_dir = { path = "../sak_dir" }
# sak_crypto = { path = "../sak_crypto" }
# chrono = "0.4"
# serde = { version = "1.0.130", features = ["derive"] }
# serde_json = "1.0.59"
# serde_bytes = "0.11.6"
# tokio = { version = "1.12.0", features = ["full"] }

[dev-dependencies]
# sak_test_utils = { path = "../sak_test_utils" }

[lib]
doctest = false
