[package]
name = "sak_store_interface"
version = "0.1.0"
edition = "2018"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.58"
sak_logger = { path = "../sak_logger" }
sak_dir = { path = "../sak_dir" }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.59"
serde_bytes = "0.11.6"
sak_types = { path = "../sak_types" }
tokio = { version = "1.21.2", features = ["full"] }

[dev-dependencies]
sak_test_utils = { path = "../sak_test_utils" }

[lib]
doctest = false
