[package]
name = "sak_mrs_contract"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
sak_contract_std = { path = "../sak_contract_std" }
sak_contract_derive = { path = "../sak_contract_derive" }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.59"
type_extension = { path = "../type_extension" }

[dev-dependencies]
sak_test_utils = { path = "../sak_test_utils" }
sak_crypto = { path = "../sak_crypto" }
sak_vm = { path = "../sak_vm" }
tokio = { version = "1.21.2", features = ["full"] }
