[package]
name = "sak_proof"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate_type = ["rlib", "staticlib", "dylib"]
doctest = false

[dependencies]
sak_crypto = { path = "../sak_crypto" }
sak_logger = { path = "../sak_logger" }
sak_dist_ledger_meta = { path = "../sak_dist_ledger_meta" }
sak_proof_circuit = { path = "../sak_proof_circuit" }
type_extension = { path = "../type_extension" }
log = "0.4.0"
jni = "0.5.2"
ff = "0.11"
pairing = "0.21.0"
sha2 = "0.9.8"
env_logger = "0.9.0"
blake2s_simd = "1.0.0"
serde_json = "1.0.59"
serde = { version = "1.0.130", features = ["derive"] }
bellman = "0.11.1"
bls12_381 = "0.6.0"

[dev-dependencies]
sak_test_utils = { path = "../sak_test_utils" }
tokio = { version = "1.12.0", features = ["full"] }
