[package]
name = "sak_proof"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
doctest = false

[dependencies]
sak_crypto = { path = "../sak_crypto" }
sak_logger = { path = "../sak_logger" }
sak_dist_ledger_config = { path = "../sak_dist_ledger_config" }
sak_proof_circuit = { path = "../sak_proof_circuit" }
type_extension = { path = "../type_extension" }
blake2s_simd = "1.0.0"
serde_json = "1.0.59"
serde = { version = "1.0.130", features = ["derive"] }
bls12_381 = "0.6.0"

[dev-dependencies]
sak_test_utils = { path = "../sak_test_utils" }
tokio = { version = "1.12.0", features = ["full"] }
