[package]
name = "sak_proof"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
doctest = false

[dependencies]
sak_crypto = { path = "../sak_crypto" }
sak_logger = { path = "../sak_logger" }
sak_ledger_cfg = { path = "../sak_ledger_cfg" }
sak_proof_circuit = { path = "../sak_proof_circuit" }
sak_proof_types = { path = "../sak_proof_types" }
type_extension = { path = "../type_extension" }
serde_json = "1.0.59"
serde = { version = "1.0.130", features = ["derive"] }
# wasm-bindgen = "0.2.83"
# getrandom = { version = "0.2", features = ["js"] }



[dev-dependencies]
sak_test_utils = { path = "../sak_test_utils" }
tokio = { version = "1.21.2", features = ["full"] }
