[package]
name = "sak_utils_net"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sak_logger = { path = "../sak_logger" }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.59"
thiserror = "1.0"
tokio = { version = "1.21.2", features = ["full"] }
colored = "2"
bytes = "1"

[lib]
doctest = false # until stable beta is released
