[package]
name = "saksaha_network"
version = "0.1.0"
edition = "2018"
default-run = "sak"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sak_logger = { path = "../sak_logger" }
sak_crypto = { path = "../sak_crypto" }
sak_kv_db = { path = "../sak_kv_db" }
sak_machine = { path = "../sak_machine" }
sak_mrs = { path = "../sak_mrs" }
sak_dir = { path = "../sak_dir" }
sak_ledger = { path = "../sak_ledger" }
sak_proof = { path = "../sak_proof" }
sak_credential = { path = "../sak_credential" }
sak_p2p_addr = { path = "../sak_p2p_addr" }
sak_p2p_peertable = { path = "../sak_p2p_peertable" }
sak_p2p_id = { path = "../sak_p2p_id" }
sak_p2p_discovery = { path = "../sak_p2p_discovery" }
sak_p2p_transport = { path = "../sak_p2p_transport" }
sak_store_interface = { path = "../sak_store_interface" }
sak_vm = { path = "../sak_vm" }
sak_vm_interface = { path = "../sak_vm_interface" }
hyper_server = { path = "../hyper_server" }
hyper_rpc_router = { path = "../hyper_rpc_router" }
sak_utils_time = { path = "../sak_utils_time" }
sak_utils_net = { path = "../sak_utils_net" }
sak_rpc_interface = { path = "../sak_rpc_interface" }
sak_task_queue = { path = "../sak_task_queue" }
sak_types = { path = "../sak_types" }
type_extension = { path = "../type_extension" }
async-trait = "0.1.58"
sak_contract_std = { path = "../sak_contract_std" }
clap = { version = "3.1.6", features = ["cargo"] }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.59"
serde_yaml = "0.8"
serde_bytes = "0.11.6"
tokio = { version = "1.21.2", features = ["full"] }
tokio-util = { version = "0.7.2", features = ["full"] }
hyper = { version = "0.14", features = ["full"] }
futures = "0.3.17"
thiserror = "1.0"
colored = "2"
chrono = "0.4"

[dev-dependencies]
sak_test_utils = { path = "../sak_test_utils" }
sak_mrs_contract = { path = "../sak_mrs_contract" }

[[bin]]
name = "sak"
path = "src/bin/sak/main.rs"

[lib]
doctest = false # until stable beta is released
