[package]
name = "sak_proof_wasm"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]
doctest = false

[dependencies]
wasm-bindgen = "0.2.83"
sak_proof_types = { path = "../sak_proof_types" }
sak_proof = { path = "../sak_proof" }
getrandom = { version = "0.2", features = ["js"] }
rayon = { version = "1.5"}
wasm-bindgen-rayon = { version = "1.0" }

[dev-dependencies]
sak_test_utils = { path = "../sak_test_utils" }
tokio = { version = "1.21.2", features = ["full"] }

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[features]
parallel = []
