[package]
name = "sak_proof_wasm"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]
doctest = false

[dependencies]
wasm-bindgen = "0.2.83"
# sak_crypto = { path = "../sak_crypto" }
# sak_logger = { path = "../sak_logger" }
# sak_ledger_cfg = { path = "../sak_ledger_cfg" }
# type_extension = { path = "../type_extension" }
# serde_json = "1.0.59"
# serde = { version = "1.0.130", features = ["derive"] }

[dev-dependencies]
sak_test_utils = { path = "../sak_test_utils" }
tokio = { version = "1.21.2", features = ["full"] }
