[package]
name = "envelope_contract"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
sak_contract_std = { path = "../../source/sak_contract_std" }
sak_contract_derive = { path = "../../source/sak_contract_derive" }
sak_types = { path = "../../source/sak_types" }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.59"
type_extension = { path = "../../source/type_extension" }

[dev-dependencies]
sak_logger = { path = "../../source/sak_logger" }
sak_test_utils = { path = "../../source/sak_test_utils" }
sak_vm = { path = "../../source/sak_vm" }
sak_vm_interface = { path = "../../source/sak_vm_interface/" }
tokio = { version = "1.21.2", features = ["full"] }
sak_mrs = { path = "../../source/sak_mrs" }
sak_credential = { path = "../../source/sak_credential" }
