[package]
name = "sak_types"
version = "0.1.0"
edition = "2018"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sak_crypto = { path = "../sak_crypto" }
sak_proof = { path = "../sak_proof" }
sak_dist_ledger_cfg = { path = "../sak_dist_ledger_cfg" }
type_extension = { path = "../type_extension" }
chrono = "0.4"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.59"
serde_bytes = "0.11.6"
colored = "2.0"

[lib]
doctest = false # until stable beta is released
