[package]
name = "envelope_term"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sak_dir = { path = "../../source/sak_dir" }
sak_logger = { path = "../../source/sak_logger" }
type_extension = { path = "../../source/type_extension" }
sak_contract_std = { path = "../../source/sak_contract_std" }
sak_crypto = { path = "../../source/sak_crypto" }
sak_ledger_cfg = { path = "../../source/sak_ledger_cfg" }
sak_types = { path = "../../source/sak_types" }
sak_kv_db = { path = "../../source/sak_kv_db" }
sak_proof = { path = "../../source/sak_proof" }
sak_proof_types = { path = "../../source/sak_proof_types" }
sak_credential = { path = "../../source/sak_credential" }
saksaha = { path = "../../source/saksaha_rs" }
saksaha_wallet = { path = "../../source/saksaha_wallet" }
log = "0.4"
tui = "0.18.0"
tui-logger = "0.8"
crossterm = "0.23"
tokio = { version = "1.21.2", features = ["full"] }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.59"
clap = { version = "3.2.14", features = ["cargo"] }
serde_yaml = "0.8"
unicode-width = "0.1.5"
chrono = "0.4"
envelope_contract = { path = "../envelope_contract" }
hyper = { version = "0.14", features = ["full"] }
sak_rpc_interface = { path = "../../source/sak_rpc_interface" }

[dev-dependencies]
sak_test_utils = { path = "../../source/sak_test_utils" }
sak_machine = { path = "../../source/sak_machine" }
sak_vm = { path = "../../source/sak_vm" }
sak_vm_interface = { path = "../../source/sak_vm_interface" }
sak_ledger = { path = "../../source/sak_ledger" }
sak_mrs = { path = "../../source/sak_mrs" }
sak_store_interface = { path = "../../source/sak_store_interface" }
async-trait = "0.1.57"

[[bin]]
name = "envelope_term"
path = "src/bin/envelope/main.rs"
