[package]
name = "sak_p2p_peertable"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sak_utils_time = { path = "../sak_utils_time" }
sak_logger = { path = "../sak_logger" }
sak_p2p_id = { path = "../sak_p2p_id" }
sak_p2p_transport = { path = "../sak_p2p_transport" }
sak_p2p_discovery = { path = "../sak_p2p_discovery" }
sak_p2p_addr = { path = "../sak_p2p_addr" }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.59"
tokio = { version = "1.12.0", features = ["full"] }
thiserror = "1.0"
log = "0.4.0"
chrono = "0.4"
colored = "2"

[lib]
doctest = false # until stable beta is released
