[package]
name = "sak_validator_contract"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
sak_contract_std = { path = "../sak_contract_std" }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.59"

[dev-dependencies]
# sak_vm = { path = "../sak_vm" }
# sak_test_utils = { path = "../sak_test_utils" }
# tokio = { version = "1.20.0", features = ["full"] }
# sak_machine = { path = "../sak_machine" }
# sak_logger = { path = "../sak_logger" }
# sak_mrs = { path = "../sak_mrs" }
# sak_store_accessor = { path = "../sak_store_accessor" }
# sak_credential = { path = "../sak_credential" }
# sak_vm_interface = { path = "../sak_vm_interface" }
