[package]
name = "sak_p2p_disc"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atoi = "0.3.2"
env_logger = { version = "0.9.0" }
bytes = "1"
sak_logger = { path = "../sak_logger" }
sak_crypto = { path = "../sak_crypto" }
chrono = "0.4"
sak_task_queue = { path = "../sak_task_queue" }
sak_p2p_addr = { path = "../sak_p2p_addr" }
sak_p2p_id = { path = "../sak_p2p_id" }
sak_p2p_frame = { path = "../sak_p2p_frame" }
sak_utils_time = { path = "../sak_utils_time" }
sak_utils_net = { path = "../sak_utils_net" }
tokio = { version = "1.12.0", features = ["full"] }
tokio-util = { version = "0.7.2", features = ["full"] }
futures = "0.3.21"
log = "0.4.0"
rand = "0.8.4"
thiserror = "1.0"
colored = "2"
lazy_static = "1.4.0"

[lib]
doctest = false # until stable beta is released
