[package]
name = "sak_test_utils"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sak_kv_db = { path = "../sak_kv_db" }
sak_fs = { path = "../sak_fs" }
sak_logger = { path = "../sak_logger" }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.59"
thiserror = "1.0"
tokio = { version = "1.12.0", features = ["full"] }
colored = "2"
bytes = "1"

[lib]
doctest = false # until stable beta is released
