[package]
name = "sak_logger"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.0"
chrono = "0.4"
colored = "2"
tracing = "0.1.36"
tracing-subscriber = { version = "0.3.15", features = ["json", "env-filter"] }
tracing-appender = "0.2.2"

[dev-dependencies]
tempfile = "3"
