[package]
name = "sak_rpc_interface"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sak_logger = { path = "../sak_logger" }
sak_crypto = { path = "../sak_crypto" }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.59"
serde_bytes = "0.11.6"
tokio = { version = "1.12.0", features = ["full"] }
sak_utils_net = { path = "../sak_utils_net" }
type_extension = { path = "../type_extension" }

[lib]
doctest = false # until stable beta is released

[dev-dependencies]
sak_test_utils = { path = "../../source/sak_test_utils" }
